boxMate/boxMate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('issuer/', include('issuer.urls')),
    path('tax/', include('taxManagement.urls')),


    # RESTFUL URLS
    path('api/issuer/', include('issuer.api.urls')),
    path('api/tax/' , include('taxManagement.api.urls')),
    path('api/codes/' , include('codes.api.urls')),

]

boxMate/home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.home_page, name='homepage'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user-login'),
    path('logout/', views.user_logout, name='logout'),

]

boxMate/issuer/urls.py
from django.urls import path

from issuer import views

app_name = 'issuer'

urlpatterns = [
    path('list/uploaded-invoices', views.list_uploaded_invoice, name='list-uploaded-invoices'),
    path('create/issuer', views.create_issuer, name='create-issuer'),
    path('list/issuer', views.list_issuer, name='list-issuer'),
    path('update/issuer/<int:issuer_id>' , views.update_issuer , name='update-issuer'),
    path('create/tax/<int:issuer_id>', views.create_issuer_tax_view, name='create-tax'),
    path('create/issuer/tax', views.create_issuer_tax, name='create-issuer-tax'), #ajax
    path('issuer/<int:issuer_id>', views.view_issuer, name='view-issuer'),
    path('issuerDB/create' , views.issuer_oracle_DB_create , name='create-issuer-db-connection'),
    path('issuerDB/list' , views.issuer_oracle_DB_list , name = 'list-issuer-db-connection'),
    path('issuerDB/import' , views.issuer_oracle_DB_import , name = 'list-issuer-db-import'),
    path('issuerDB/cancel' , views.issuer_oracle_DB_cancel , name = 'list-issuer-db-cancel'),
    path('issuerDB/update/<int:id>' , views.issuer_oracle_DB_update , name = 'update-issuer-db-connection'),
    path('issuerDB/activate/<int:id>',views.activate_database,name='activate-db'),
    path('create/receiver' , views.create_receiver , name = 'create-receiver'),
    path('list/receiver' , views.list_receiver , name='list-receiver'),
    path('list/receiver/<int:pk>' , views.update_receiver , name='update-receiver'),
    path('delete/receiver/<int:pk>' , views.delete_receiver , name='delete-receiver'),
    path('view/receiver/<int:pk>' , views.view_receiver , name='view-receiver'),
    path('create/address/issuer' , views.create_issuer_address,name='create-issuer-address'),
    path('list/address/issuer' , views.list_issuer_address,name='list-issuer-address'),
    path('update/address/issuer/<int:id>' , views.update_issuer_address,name='update-issuer-address'),
    path('delete/address/issuer/<int:id>' , views.delete_issuer_address,name='delete-issuer-address'),

    path('export/receiver-template', views.export_receiver_template, name='export-receiver-template'),
    path('import/receiver-template', views.import_receiver_template, name='import-receiver-template'),


]

boxMate/taxManagement/urls.py
from django.urls import path

from taxManagement import views

app_name = 'taxManagement'
urlpatterns = [
    path('upload/', views.upload_excel_sheet, name='upload-tax'),
    path('list/uploaded-invoices', views.get_all_invoice_headers , name='get-all-invoice-headers'),
    path('connect/get-data', views.import_data_from_db , name='connect-oracle'),

    # path('invoice-headers/' , views.get_all_invoice_headers , name='get-all-invoice-headers')
    path('list/eta-invoice/', views.list_eta_invoice, name='list-eta-invoice'),
    path('submit-invoice/<slug:invoice_id>', views.submit_invoice , name='submit-invoice'),
    path('document-detail/<slug:internal_id>/', views.get_decument_detail_after_submit , name='dec-detail'),
    path('upload-excel-sheet/' , views.upload_excel_sheet, name='upload-excel-sheet'),
    path('resubmit-invoice/<slug:invoice_id>', views.resubmit, name='resubmit-invoice'),
    path('view-invoice/<slug:invoice_id>' , views.view_invoice , name = 'view-invoice'),
    path('create-invoice-header' , views.create_new_invoice_header , name='create-invoice-header'),
    path('create-invoice-line/<int:invoice_id>' , views.create_new_invoice_line , name='create-invoice-line'),
    path('refresh-submission-status/<slug:submission_id>' , views.refresh_submission_status , name='refresh-submission-status'),

    path('tax/change-invoice-status/<int:invoice_id>/<slug:status>', views.update_invoice_status, name="update-invoice-status"),

    path('export/invoice-template', views.export_empty_invoice_temp, name="export_excel_template"),

    path('ajax/load-addresses/', views.load_receiver_addresses, name='ajax_load_addresses'),

    path('cancel-invoice/<slug:doc_uuid>/', views.cancel_document_form, name="cancel_doc_form"),

    path('list/print-invoice/', views.list_print_invoice, name='list_print_invoice'),
    path('print-invoice/<slug:doc_uuid>', views.print_invoice, name='print_invoice'),
    path('ajax/load-subtasks/', views.load_subtasks, name='ajax_load_subtasks'),

]

boxMate/boxMate/templates/footer.html
{% load static %}
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.2.0
    </div>
    <strong>Copyright &copy; 2021 <a href="https://www.arkleap.com/" target="_blank">Arkleap Technologies</a>.</strong> All rights reserved.
</footer>

boxMate/boxMate/templates/login.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr" xmlns="http://www.w3.org/1999/html">

<head>
    <meta charset="utf-8">
    <title></title>
    <title>BooksMate</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link rel="stylesheet" href="{% static 'src/font/iconsmind-s/css/iconsminds.css' %}"/>
    <link rel="stylesheet" href="{% static 'src/font/simple-line-icons/css/simple-line-icons.css' %}"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">


</head>
<div class="container">
<div class="card bg-light">
    <article class="card-body mx-auto" style="max-width: 400px;">
        <h4 class="card-title mt-3 text-center">Login</h4>

              <form method="POST" id="login-form" class="form" action="">
                {% csrf_token %}
                <div class="form-group">
                <label class="form-group has-float-label mb-4"><span>Username</span></label>
                  <input class="form-control" name="username" />
                </div>
                <div class="form-group">
                <label class="form-group has-float-label mb-4"><span>Password</span></label>
                  <input class="form-control" name="password" type="password" placeholder=""/>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                  <button class="btn btn-primary btn-block" type="submit">LOGIN</button>
                </div>
                

              </form>
    </article>
</div>
</div>


</html>

boxMate/boxMate/templates/main.html
<!DOCTYPE html>
{% load static  %}
{% load i18n %}
{% load l10n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
<html>
   <head>
      <meta charset="UTF-8">
      <title>BooksMate</title>
      <!-- Tell the browser to be responsive to screen width -->
      <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
      <!-- Bootstrap 3.3.4 -->

      <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
      <link href="{% static 'bootstrap/css/accordion.css' %}" rel="stylesheet" type="text/css" />
      <!-- FontAwesome 4.3.0 -->
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
      <!-- Ionicons 2.0.0 -->
      <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
      <!-- Theme style -->
      <link href="{% static 'dist/css/AdminLTE.min.css' %}" rel="stylesheet" type="text/css" />
      <link href="{% static 'dist/css/skins/_all-skins.min.css' %}" rel="stylesheet" type="text/css" />
      <!-- iCheck -->
      <link href="{% static 'plugins/iCheck/flat/blue.css' %}" rel="stylesheet" type="text/css" />
      <!-- Morris chart -->
      <link href="{% static 'plugins/morris/morris.css' %}" rel="stylesheet" type="text/css" />
      <!-- jvectormap -->
      <link href="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet" type="text/css" />
      <!-- Date Picker -->
      <link href="{% static 'plugins/datepicker/datepicker3.css' %}" rel="stylesheet" type="text/css" />
      <!-- Daterange picker -->
      <link href="{% static 'plugins/daterangepicker/daterangepicker-bs3.css' %}" rel="stylesheet" type="text/css" />
      <!-- bootstrap wysihtml5 - text editor -->
      <link href="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}" rel="stylesheet" type="text/css" />


   </head>
   <body class="skin-blue sidebar-mini">
      <div class="wrapper">
         <header class="main-header">
            <!-- Logo -->
            <a href="{% url 'home:homepage' %}" class="logo">
               <!-- mini logo for sidebar mini 50x50 pixels -->
               <span class="logo-mini"><b>B</b>M8</span>
               <!-- logo for regular state and mobile devices -->
               <span class="logo-lg"><b>Books</b>Mate</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            {% include 'top-bar.html' %}
         </header>
         <!-- Left side column. contains the logo and sidebar -->
         <aside class="main-sidebar">
            {% include 'side-bar.html' %}
         </aside>
         <!-- Content Wrapper. Contains page content -->

         {% block body %}
         {% endblock body %}

         <!-- /.content-wrapper -->
         {% include 'footer.html' %}
         <!-- Add the sidebar's background. This div must be placed
            immediately after the control sidebar -->
         <div class="control-sidebar-bg"></div>
      </div>
      <!-- ./wrapper -->
      <!-- jQuery 2.1.4 -->
            <script src="{% static 'plugins/jQuery/jquery-3.6.0.min.js' %}"></script>
      <!-- jQuery UI 1.11.4 -->
      <script src="{% static 'plugins/jQueryUI/jquery-ui.min.js' %}" type="text/javascript"></script>  

      <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
      <script type="text/javascript">
         $.widget.bridge('uibutton', $.ui.button);
      </script>
      <!-- Bootstrap 3.3.2 JS -->
      <script src="{% static 'bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
      <!-- Morris.js charts -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
      <script src="{% static 'plugins/morris/morris.min.js' %}" type="text/javascript"></script>
      <!-- Sparkline -->
      <script src="{% static 'plugins/sparkline/jquery.sparkline.min.js' %}" type="text/javascript"></script>
      <!-- jvectormap -->
      <script src="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}" type="text/javascript"></script>
      <script src="{% static 'plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}" type="text/javascript"></script>
      <!-- jQuery Knob Chart -->
      <script src="{% static 'plugins/knob/jquery.knob.js' %}" type="text/javascript"></script>
      <!-- daterangepicker -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js" type="text/javascript"></script>
      <script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}" type="text/javascript"></script>
      <!-- datepicker -->
      <script src="{% static 'plugins/datepicker/bootstrap-datepicker.js' %}" type="text/javascript"></script>
      <!-- Bootstrap WYSIHTML5 -->
      <script src="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}" type="text/javascript"></script>
      <!-- Slimscroll -->
      <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
      <!-- FastClick -->
      <!-- FastClick -->
      <script src="{% static 'plugins/fastclick/fastclick.min.js' %}" type="text/javascript"></script>
      <!-- AdminLTE App -->
      <script src="{% static 'dist/js/app.min.js' %}" type="text/javascript"></script>
      <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
      <script src="{% static 'dist/js/pages/dashboard.js' %}" type="text/javascript"></script>
      <!-- AdminLTE for demo purposes -->
      <script src="{% static 'dist/js/demo.js' %}" type="text/javascript"></script>
      <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.23/af-2.3.5/b-1.6.5/b-colvis-1.6.5/b-flash-1.6.5/b-print-1.6.5/cr-1.5.3/fc-3.3.2/kt-2.6.1/r-2.2.7/rg-1.1.2/rr-1.2.7/sc-2.0.3/sb-1.0.1/sp-1.2.2/sl-1.3.1/datatables.min.css"/>

      <script type="text/javascript"
      src="https://cdn.datatables.net/v/dt/dt-1.10.23/af-2.3.5/b-1.6.5/b-colvis-1.6.5/b-flash-1.6.5/b-print-1.6.5/cr-1.5.3/fc-3.3.2/kt-2.6.1/r-2.2.7/rg-1.1.2/rr-1.2.7/sc-2.0.3/sb-1.0.1/sp-1.2.2/sl-1.3.1/datatables.min.js">
      </script>
      <script>
         $(document).ready(function() {
    $('#example').DataTable();
} );
      </script>


      
{% block js %}
{% endblock js %}



   </body>
</html>

boxMate/boxMate/templates/messages.html
{% load static %}
{% load i18n %}
{% load l10n %}

{% if messages %}
  {% for message in messages %}
    {% if message.tags == "success" %}
        <div class="alert alert-success alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Success!</strong> {{ message|safe }}.
          </div>
        {% elif message.tags == "info" %}
        <div class="alert alert-info alert-dismissible">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <strong>Info!</strong> {{ message|safe }}.
        </div>
        {% elif message.tags == "warning" %}
        <div class="alert alert-warning alert-dismissible">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <strong>Warning!</strong> {{ message|safe }}.
        </div>
        {% elif message.tags == "error" %}
        <div class="alert alert-danger alert-dismissible">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <strong>Danger!</strong> {{ message|safe }}.
        </div>
    {% endif %}
  {% endfor %}
{% endif %}

boxMate/boxMate/templates/register.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr" xmlns="http://www.w3.org/1999/html">

<head>
    <meta charset="utf-8">
    <title></title>
    <title>BooksMate</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link rel="stylesheet" href="{% static 'src/font/iconsmind-s/css/iconsminds.css' %}"/>
    <link rel="stylesheet" href="{% static 'src/font/simple-line-icons/css/simple-line-icons.css' %}"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">


</head>
<div class="container">
<div class="card bg-light">
    <article class="card-body mx-auto" style="max-width: 400px;">
        <h4 class="card-title mt-3 text-center">Create Account</h4>

        <form method="post">
            {% csrf_token %}
            {{ register_form.username.label_tag }}<br>
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                </div>
                    {{register_form.username}}
                    <small style="color: grey">{{ register_form.username.help_text }}</small>
                    {% for error in register_form.username.errors %}
                         <p style="color: red">{{ error }}</p>
                    {% endfor %}
            </div> <!-- form-group// -->
            {{ register_form.password1.label_tag }}<br>
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                </div>
                {{register_form.password1}}
                <small style="color: grey">{{ register_form.password1.help_text }}</small>
                 {% for error in register_form.password1.errors %}
                         <p style="color: red">{{ error }}</p>
                {% endfor %}

            </div> <!-- form-group// -->
            {{ register_form.password2.label_tag }}<br>
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                </div>
                {{register_form.password2}}
                <p class="help-block" style="color: grey">{{ register_form.password2.help_text }}</p>
                {% for error in register_form.password2.errors %}
                         <p style="color: red">{{ error }}</p>
                {% endfor %}
            </div> <!-- form-group// -->

            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block"> Create Account</button>
            </div> <!-- form-group// -->
            <p class="text-center">Have an account? <a href="{% url 'home:user-login' %}">Log In</a></p>

        </form>
    </article>

</div>
</div>
</html>

boxMate/boxMate/templates/side-bar.html
{% load static %}
<!-- sidebar: style can be found in sidebar.less -->
<section class="sidebar">
  <ul class="sidebar-menu">
    <li class="header">MAIN NAVIGATION</li>
    <li><a href="{% url 'home:homepage' %}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
    <li class="treeview">
      <a href="#">
        <i class="fa fa-files-o"></i>
        <span>Setup Pages</span>
        <i class="fa fa-angle-right pull-right"></i>
      </a>
      <ul class="treeview-menu">

        <li><a href="{% url 'issuer:list-issuer-db-connection' %}"><i class="fa fa-circle-o"></i>Oracle DB
            Connections</a></li>
        <li><a href="{% url 'issuer:list-issuer' %}"><i class="fa fa-circle-o"></i>List Issuer</a></li>
        <li><a href="{% url 'issuer:list-receiver' %}"><i class="fa fa-circle-o"></i>List Receiver</a></li>
      </ul>
    </li>
    <li class="header">Invoices Section</li>
    <li class="treeview">
      <a href="#">
        <i class="fa fa-files-o"></i>
        <span>Tax Invoice</span>
        <i class="fa fa-angle-right pull-right"></i>
      </a>
      <ul class="treeview-menu">
        <li><a href="{% url 'taxManagement:get-all-invoice-headers' %}"><i class="fa fa-circle-o"></i>Upload Invoice</a></li>
        <li><a href="{% url 'taxManagement:list-eta-invoice' %}"><i class="fa fa-circle-o"></i>ETA Invoice</a></li>
        <li><a href="{% url 'taxManagement:list_print_invoice' %}"><i class="fa fa-circle-o"></i>Print Invoice</a></li>

      </ul>
    </li>
  </ul>
</section>
<!-- /.sidebar -->

boxMate/boxMate/templates/top-bar.html
{% load static %}
{% load i18n %}
{% load l10n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}
<nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
            <!-- User Account: style can be found in dropdown.less -->

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-language"> {{ LANGUAGE_CODE|language_name_translated }}</i>
                </a>

                        <!-- inner menu: contains the actual data -->
               <ul class="dropdown-menu" role="menu" id="language-list">
                {% for language in languages %}
                    <li>
                      <a href="{% url 'set_language' %}" data-language-code="{{ language.code }}">
                        {% if language.code == LANGUAGE_CODE %}&#10003;{% else %}&nbsp;&nbsp;{% endif %}
                        {{ language.name_local }}
                      </a>
                    </li>
                {% endfor %}
              </ul>

            </li>
            <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <span class="hidden-xs">Welcome: </span>
                    <span class="hidden-xs">{{ request.user|capfirst }}</span>
                </a>
                <ul class="dropdown-menu">
                    <!-- User image -->
                    <li class="user-header">
                        <img src="{% static 'dist/img/teacher.jpeg' %}" class="img-circle" alt="User Image"/>
                        <p>
                            {{ request.user.username|capfirst }}
                        </p>
                    </li>
                    <li class="user-footer">
                        {% if request.user.is_superuser %}
                        <div class="pull-left">
                            <a href="{% url 'home:register' %}" class="btn btn-default btn-flat">Register New User</a>
                        </div>
                        {% endif %}
                        <div class="pull-right">
                            <a href="{% url 'home:logout' %}" class="btn btn-default btn-flat">Log out</a>
                        </div>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>
<!-- jQuery 2.1.4 -->
<script src="{% static 'plugins/jQuery/jquery-3.6.0.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'plugins/jQueryUI/jquery-ui.min.js' %}" type="text/javascript"></script>
<script>
    $('#language-list a').on('click', function(event) {
        event.preventDefault();
        var target = $(event.target);
        var url = target.attr('href');
        var language_code = target.data('language-code');
        $.ajax({
            type: 'POST',
            url: url,
            data: {language: language_code},
            headers: {"X-CSRFToken": getCookie('csrftoken')}
        }).done(function(data, textStatus, jqXHR) {
            reload_page();
        });
    });
</script>
<script>
    function getCookie(name) {
        var value = '; ' + document.cookie,
            parts = value.split('; ' + name + '=');
        if (parts.length == 2) return parts.pop().split(';').shift();
    }

    function reload_page() {
        window.location.reload(true);
    }
</script>