boxMate/boxMate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('issuer/', include('issuer.urls')),
    path('tax/', include('taxManagement.urls')),


    # RESTFUL URLS
    path('api/issuer/', include('issuer.api.urls')),
    path('api/tax/' , include('taxManagement.api.urls')),
    path('api/codes/' , include('codes.api.urls')),

]

boxMate/home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.home_page, name='homepage'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user-login'),
    path('logout/', views.user_logout, name='logout'),

]

boxMate/issuer/api/urls.py
from django.urls import path

from issuer.api import views

urlpatterns = [
    path('create/', views.add_issuer, name='create-issuer'),
    path('list/', views.IssuerListView.as_view(), name='list-issuers'),
]

boxMate/issuer/urls.py
from django.urls import path

from issuer import views

app_name = 'issuer'

urlpatterns = [
    path('list/uploaded-invoices', views.list_uploaded_invoice, name='list-uploaded-invoices'),
    path('create/issuer', views.create_issuer, name='create-issuer'),
    path('list/issuer', views.list_issuer, name='list-issuer'),
    path('update/issuer/<int:issuer_id>' , views.update_issuer , name='update-issuer'),
    path('create/tax/<int:issuer_id>', views.create_issuer_tax_view, name='create-tax'),
    path('create/issuer/tax', views.create_issuer_tax, name='create-issuer-tax'), #ajax
    path('issuer/<int:issuer_id>', views.view_issuer, name='view-issuer'),
    path('issuerDB/create' , views.issuer_oracle_DB_create , name='create-issuer-db-connection'),
    path('issuerDB/list' , views.issuer_oracle_DB_list , name = 'list-issuer-db-connection'),
    path('issuerDB/import' , views.issuer_oracle_DB_import , name = 'list-issuer-db-import'),
    path('issuerDB/cancel' , views.issuer_oracle_DB_cancel , name = 'list-issuer-db-cancel'),
    path('issuerDB/update/<int:id>' , views.issuer_oracle_DB_update , name = 'update-issuer-db-connection'),
    path('issuerDB/activate/<int:id>',views.activate_database,name='activate-db'),
    path('create/receiver' , views.create_receiver , name = 'create-receiver'),
    path('list/receiver' , views.list_receiver , name='list-receiver'),
    path('list/receiver/<int:pk>' , views.update_receiver , name='update-receiver'),
    path('delete/receiver/<int:pk>' , views.delete_receiver , name='delete-receiver'),
    path('view/receiver/<int:pk>' , views.view_receiver , name='view-receiver'),
    path('create/address/issuer' , views.create_issuer_address,name='create-issuer-address'),
    path('list/address/issuer' , views.list_issuer_address,name='list-issuer-address'),
    path('update/address/issuer/<int:id>' , views.update_issuer_address,name='update-issuer-address'),
    path('delete/address/issuer/<int:id>' , views.delete_issuer_address,name='delete-issuer-address'),

    path('export/receiver-template', views.export_receiver_template, name='export-receiver-template'),
    path('import/receiver-template', views.import_receiver_template, name='import-receiver-template'),


]

boxMate/issuer/models.py
from django.contrib.auth.models import User
from datetime import datetime, date
from django.utils import timezone
from django.db import models
from django.db import transaction
from codes.models import CountryCode, TaxTypes, ActivityType , TaxSubtypes
from django.conf import settings


# Create your models here.
class Issuer(models.Model):
    type = models.CharField(max_length=8,
                            choices=[('B', 'business'), ('P', 'natural person'), ('F', 'foreigner')], default='B')
    reg_num = models.CharField(max_length=20, verbose_name='reg_number', unique=True)
    name = models.CharField(max_length=50, verbose_name='issuer name', blank=True, null=True)
    client_id = models.CharField(max_length=50,blank=True, null=True )
    clientSecret1 = models.CharField(max_length=50,blank=True, null=True)
    clientSecret2 = models.CharField(max_length=50,blank=True, null=True)
    activity_code = models.ForeignKey(ActivityType, on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateField(auto_now_add=True, null=True, blank=True)
    last_updated_at = models.DateField(null=True, auto_now=True, auto_now_add=False, blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True,
                                   related_name="Issuer_created_by")
    last_updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True, related_name="Issuer_last_updated_by")

    def __str__(self):
        return self.name


class Receiver(models.Model):
    issuer = models.ForeignKey(Issuer , on_delete=models.CASCADE) #### by:Mamdouh
    type = models.CharField(max_length=8,
                            choices=[('B', 'business'), ('P', 'natural person'), ('F', 'foreigner')], default='B')
    reg_num = models.CharField(max_length=20, verbose_name='reg_number')
    name = models.CharField(max_length=50, verbose_name='reciever name', blank=True, null=True)
    created_at = models.DateField(auto_now_add=True, null=True, blank=True)
    last_updated_at = models.DateField(null=True, auto_now=True, auto_now_add=False, blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True,
                                   related_name="Receiver_created_by")
    last_updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)


    def __str__(self):
        return self.name

class Address(models.Model):
    branch_id = models.CharField(max_length=10)
    issuer = models.ForeignKey(Issuer, on_delete=models.CASCADE, null=True, blank=True, related_name='issuer_addresses')
    receiver = models.ForeignKey(Receiver, on_delete=models.CASCADE, null=True, blank=True,related_name='rec_addresses')
    country = models.ForeignKey(CountryCode, on_delete=models.CASCADE, blank=True, null=True)
    governate = models.CharField(max_length=50, blank=True, null=True)
    regionCity = models.CharField(max_length=50, blank=True, null=True)
    street = models.CharField(max_length=120, blank=True, null=True)
    buildingNumber = models.CharField(max_length=120, blank=True, null=True)
    postalCode = models.CharField(max_length=20, blank=True, null=True)
    floor = models.CharField(max_length=10, blank=True, null=True)
    room = models.CharField(max_length=10, blank=True, null=True)
    landmark = models.CharField(max_length=120, blank=True, null=True)
    additionalInformation = models.CharField(max_length=250, blank=True, null=True)
    created_at = models.DateField(auto_now_add=True, null=True, blank=True)
    last_updated_at = models.DateField(null=True, auto_now=True, auto_now_add=False, blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True,
                                   related_name="address_created_by")
    last_updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.branch_id



class IssuerTax(models.Model):
    issuer = models.ForeignKey(Issuer, on_delete=models.CASCADE, null=True, blank=True, related_name='issuer_tax')
    issuer_sub_tax = models.ForeignKey(TaxSubtypes, on_delete=models.CASCADE, null=True, blank=True, related_name='issuer_sub_tax')
    start_date = models.DateField(default=timezone.now, null=True, blank=True)
    end_date = models.DateField(null=True, blank=True) # By: amira/ removed auto now to not be set in creation time
    is_enabled = models.BooleanField()

    created_at = models.DateField(auto_now_add=True, null=True, blank=True)
    last_updated_at = models.DateField(null=True, auto_now_add=False, blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True,
                                   related_name="issuer_tax_created_by")
    last_updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True, related_name="issuer_tax_last_update_by")

    def __str__(self):
        return self.issuer.name

class IssuerOracleDB(models.Model):
    issuer = models.ForeignKey(Issuer,on_delete=models.CASCADE)
    ip_address = models.CharField(max_length=20)
    port_number = models.CharField(max_length=10)
    service_number = models.CharField(max_length=10)
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=100)
    database_name = models.CharField(max_length=50)
    is_active = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.is_active:
            return super(IssuerOracleDB, self).save(*args, **kwargs)
        with transaction.atomic():
            IssuerOracleDB.objects.filter(
                is_active=True , issuer=self.issuer).update(is_active=False)
            return super(IssuerOracleDB, self).save(*args, **kwargs)


class IssuerActivityCode(models.Model):
    issuer = models.ForeignKey(Issuer,on_delete=models.CASCADE)
    activity_code = models.ForeignKey(ActivityType, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.issuer.name + ' - ' + self.activity_code.code

boxMate/issuer/forms.py
from django import forms
from issuer.models import Issuer ,IssuerTax, Address , IssuerOracleDB , Receiver, IssuerActivityCode
from datetime import date
from django.forms import modelformset_factory , formset_factory, inlineformset_factory


def clean_unique(form, field, exclude_initial=True,
                 format="The %(field)s %(value)s has already been taken."):
    value = form.cleaned_data.get(field)
    if value:
        qs = form._meta.model._default_manager.filter(**{field:value})
        if exclude_initial and form.initial:
            initial_value = form.initial.get(field)
            qs = qs.exclude(**{field:initial_value})
        if qs.count() > 0:
            raise forms.ValidationError(format % {'field':field, 'value':value})
    return value

class IssuerForm(forms.ModelForm):
    class Meta:
        model = Issuer
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        update = kwargs.pop('update')
        super(IssuerForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
        if update:
            self.fields['reg_num'].widget.attrs['readonly'] = True
            self.fields['client_id'].widget.attrs['readonly'] = True
            self.fields['activity_code'].widget.attrs['readonly'] = True
            self.fields['type'].widget.attrs['disabled'] = True
            self.fields['type'].required = False







class IssuerTaxForm(forms.ModelForm):
    class Meta:
        model = IssuerTax
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super(IssuerTaxForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'



class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AddressForm, self).__init__(*args, **kwargs)
        self.fields['country'].widget.attrs.update(width=200)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
modelformset_factory
class IssuerOracleDBForm(forms.ModelForm):
    class Meta:
        model = IssuerOracleDB
        fields = '__all__'
        exclude = {'issuer',}
    def __init__(self , *args , **kwargs):
        super(IssuerOracleDBForm , self).__init__(*args , **kwargs)


class ReceiverForm(forms.ModelForm):
    class Meta:
        model = Receiver
        fields = '__all__'
        exclude = ('issuer',)
    def __init__(self, *args, **kwargs):
        super(ReceiverForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

AddressInlineForm = modelformset_factory(Address, form=AddressForm, extra=1)

class ActivityCodeForm(forms.ModelForm):
    class Meta:
        model = IssuerActivityCode
        fields = '__all__'
    def __init__(self, *args, **kwargs):
            super(ActivityCodeForm, self).__init__(*args, **kwargs)
            for field in self.fields:
                self.fields[field].widget.attrs['class'] = 'form-control'

ActivityCodeInlineForm = inlineformset_factory(Issuer,IssuerActivityCode ,form=ActivityCodeForm, extra=0)

boxMate/issuer/api/views.py
from django.db import IntegrityError
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import status
from rest_framework.filters import OrderingFilter
from rest_framework.generics import ListAPIView
from rest_framework.pagination import PageNumberPagination
from rest_framework.response import Response
from rest_framework.decorators import api_view
from issuer.models import *
from issuer.api.serializers import IssuerSerializer
from taxManagement.models import *
from django.db.models import Count
from django.utils import timezone
from django.shortcuts import render, redirect
from codes.models import CountryCode
from django.shortcuts import get_object_or_404

# Create your views here.
@api_view(['POST', ])
def add_issuer(request):
    issuer_serializer = IssuerSerializer(data=request.data)
    if issuer_serializer.is_valid():
        try:
            issuer_serializer.save()
        except Exception as e:
            print(e)
            data = {"success": False, "error": {"code": 400, "message": "Issuer not created"}}
            return Response(data, status=status.HTTP_400_BAD_REQUEST)
        data = {"success": True, "data": issuer_serializer.data}
        return Response(data, status=status.HTTP_201_CREATED)
    else:
        data = {"success": False, "error": {"code": 400, "message": issuer_serializer.errors}}
        return Response(data, status=status.HTTP_400_BAD_REQUEST)


class IssuerListView(ListAPIView):
    serializer_class = IssuerSerializer
    filter_backends = (DjangoFilterBackend, OrderingFilter)
    filter_fields = ('id', 'reg_num',)
    ordering_fields = ('id',)
    pagination_class = PageNumberPagination

    def get_queryset(self):
        return Issuer.objects.all()

    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())
        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            paginated_response = self.get_paginated_response(serializer.data)
            data = {"success": True, "count": paginated_response.data["count"], "data": serializer.data, }
            return Response(data)

        serializer = self.get_serializer(queryset, many=True)
        data = {"success": True, "data": serializer.data}
        return Response(data)

boxMate/issuer/templates/list-issuer-addresses.html
{% extends 'main.html'%}
{% load static %}
{% load l10n %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block body %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">

        <div class="box">
            <div class="box-header">
                <h1 style="font-weight: bolder;">
                    {% trans 'Addresses' %}
                    <a href="{% url 'issuer:create-issuer-address' %}"  data-toggle="tooltip" title="{% trans 'Create' %}" class="pull-right btn btn-success">
                        {% trans 'Create New Address' %}
                    </a>
                    <a href="{% url 'issuer:list-issuer' %}"  data-toggle="tooltip" title="{% trans 'Back to Addresses' %}" class="pull-right btn btn-warning" style="margin-right: 2px;">
                        {% trans 'Back to Addresses' %}
                    </a>

                    <!-- <small>Optional description</small> -->
                </h1>
            </div>
            <div class="box-body">
                {% for address in addresses %}
                <div class="form-row">
                    <div class="form-group col-md-12" style="font-size: larger; font-weight: bolder;">
                        {% trans 'Address' %} #{{forloop.counter}}
                        <a href="{% url 'issuer:update-issuer-address' address.id %}" style="margin-left: 3%;" data-toggle="tooltip" title="{% trans 'Edit' %}">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                        <a href="{% url 'issuer:delete-issuer-address' address.id %}" style="margin-left: 3%;" data-toggle="tooltip" title="{% trans 'Delete' %}">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                    </div>
                    
                    <div class="form-group col-md-4" style="font-size: larger;">
                        <label for="formGroupExampleInput" class="form-label">{% trans 'Branch' %} : </label>
                        {{address.branch_id}}
                    </div>
                    <div class="form-group col-md-4" style="font-size: larger;">
                        <label for="formGroupExampleInput2" class="form-label">{% trans 'Governate' %} : </label>
                        {{address.governate}}
                    </div>

                    <div class="form-group col-md-4" style="font-size: larger;">
                        <label for="formGroupExampleInput2" class="form-label">{% trans 'Region City' %} : </label>
                        {{address.regionCity}}
                    </div>

                    <div class="form-group col-md-4" style="font-size: larger;">
                        <label for="formGroupExampleInput2" class="form-label">{% trans 'Street' %} : </label>
                        {{address.street}}
                    </div>

                    <div class="form-group col-md-4" style="font-size: larger;">
                        <label for="formGroupExampleInput2" class="form-label">{% trans 'Building Number' %} : </label>
                        {{address.buildingNumber}}
                    </div>

                    <div class="form-group col-md-4" style="font-size: larger;">
                        <label for="formGroupExampleInput2" class="form-label">{% trans 'Postal Code' %} : </label>
                        {{address.postalCode}}
                    </div>
                </div>
                {% endfor %}

                <br>
            </div>
        </div>
    </section>
</div>

{% endblock body %}

boxMate/issuer/templates/list-issuer.html
{% extends 'main.html'%}
{% load static %}
{% load l10n %}
{% load i18n %}

{% block body %}
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      {% trans 'Issuers' %}
    </h1>

  </section>
  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-body">
            <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
              <div class="col-sm-6">

              </div>
              <div class="row">
                <div class="col-sm-12">
                  <table id="example1" class="table table-bordered table-striped dataTable" role="grid"
                    aria-describedby="example1_info">
                    <thead>
                      <tr role="row">
                        <th>#</th>
                        <th>{% trans 'Name' %}</th>
                        <th>{% trans 'Registration Number' %}</th>
                        <th>{% trans 'Client ID' %}</th>
                        <th>{% trans 'Addresses' %}</th>
                        <th>{% trans 'Action' %}</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for issuer in issuers_list %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ issuer.name }}</td>
                        <td>{{ issuer.reg_num }}</td>
                        <td>{{ issuer.client_id }}</td>
                        <td>
                          <a href="{% url 'issuer:list-issuer-address' %}" data-toggle="tooltip" title="{% trans 'View Address' %}">
                            <span class="glyphicon glyphicon-zoom-in"></span>
                          </a>
                        </td>
                        <td style="display: flex; justify-content: space-around;">
                          <a href="{% url 'issuer:view-issuer' issuer.id %}" data-toggle="tooltip" title="{% trans 'View Issuer' %}">
                            <span class="glyphicon glyphicon-zoom-in"></span>
                          </a>
                          <a href="{% url 'issuer:update-issuer' issuer.id %}" data-toggle="tooltip" title="{% trans 'Edit' %}">
                            <span class="glyphicon glyphicon-pencil"></span>
                          </a>
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>

                  </table>
                </div>
              </div>
            </div>
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
</div>


{% endblock body %}

boxMate/issuer/templates/list-receiver.html
{% extends 'main.html'%}
{% load static %}
{% load l10n %}
{% load i18n %}

{% block body %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            {% trans 'Receivers' %}
            <!-- <small>Optional description</small> -->
        </h1>

    </section>
    <!-- Main content -->
    <section class="content">
        {% include 'messages.html' %}
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body">
                        <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                            <div class="col-sm-12">
                                <div class="margin pull-right">
                                    <a href="{% url 'issuer:create-receiver' %}" class="btn btn-primary margin-bottom">
                                        {% trans 'Add Receiver' %}
                                    </a>
                                    <button type="button" class="btn btn-success margin-bottom" data-toggle="modal"
                                       data-target="#exampleModal" style="margin-right: 2px;">
                                       {% trans "Upload Excel" %}
                                    </button>
                                    <a href="{% url 'issuer:export-receiver-template' %}" class="btn btn-warning margin-bottom ">
                                       {% trans 'Export Excel Template' %}
                                    </a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <table id="example1" class="table table-bordered table-striped dataTable"
                                        role="grid" aria-describedby="example1_info">
                                        <thead>
                                            <tr role="row">
                                                <th>#</th>
                                                <th style="text-align: center;">{% trans 'Name' %}</th>
                                                <th style="text-align: center;">{% trans 'Registration Number' %}</th>
                                                <th style="text-align: center;">{% trans 'Type' %}</th>
                                                <th style="text-align: center;">{% trans 'Action' %}</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for receiver in receivers %}
                                            <tr>
                                                <td>{{ forloop.counter }}</td>
                                                <td style="text-align: center;">{{ receiver.name }}</td>
                                                <td style="text-align: center;">{{ receiver.reg_num }}</td>
                                                <td style="text-align: center;">{{ receiver.get_type_display }}</td>
                                                <td style="display: flex; justify-content: space-around;">
                                                    <a href="{% url 'issuer:view-receiver' receiver.id %}"
                                                        data-toggle="tooltip" title="{% trans 'View Receiver' %}">
                                                        <span class="glyphicon glyphicon-zoom-in"></span>
                                                    </a>

                                                    <a href="{% url 'issuer:update-receiver' receiver.id %}"
                                                        data-toggle="tooltip" title="{% trans 'Edit' %}">
                                                        <span class="glyphicon glyphicon-pencil"></span>
                                                    </a>
                                                    {% if receiver.receiver_val.count > 0 %}
                                                      <a href="#"
                                                          data-toggle="tooltip" title="{% trans 'Delete' %}"
                                                          onclick="delete_alert()">
                                                          <span class="glyphicon glyphicon-trash"></span>
                                                      </a>
                                                    {% else %}
                                                      <a href="{% url 'issuer:delete-receiver' receiver.id %}"
                                                          data-toggle="tooltip" title="{% trans 'Delete' %}"
                                                          onclick="return confirm('Are you sure?')">
                                                          <span class="glyphicon glyphicon-trash"></span>
                                                      </a>
                                                    {% endif%}
                                                </td>

                                            </tr>
                                            {% endfor %}
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
   aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <form method="POST" action="{% url 'issuer:import-receiver-template' %}" id="form1" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal-body">
               <input type="file" name="import_file">
            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
               <button type="submit" class="btn btn-secondary" data-dismiss="modal" onclick="document.getElementById('form1').submit();">Submit</button>

            </div>
         </form>
      </div>
   </div>
</div>


{% endblock body %}

{% block js %}
<script type="text/javascript">
  function delete_alert(){
    alert("Can't delete this receiver as he has invoices");
  }
</script>
{% endblock js %}