boxMate/boxMate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('issuer/', include('issuer.urls')),
    path('tax/', include('taxManagement.urls')),


    # RESTFUL URLS
    path('api/issuer/', include('issuer.api.urls')),
    path('api/tax/' , include('taxManagement.api.urls')),
    path('api/codes/' , include('codes.api.urls')),

]

boxMate/home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.home_page, name='homepage'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user-login'),
    path('logout/', views.user_logout, name='logout'),

]

boxMate/taxManagement/api/urls.py
from django.urls import path

from taxManagement.api import views

app_name = 'tax'
urlpatterns = [
    path('upload/', views.upload_excel_sheet, name='upload-tax'),
    path('invoice-headers/' , views.get_all_invoice_headers , name='get-all-invoice-headers'),
    path('subm_list/', views.submission_list, name='submission-list'),
]

boxMate/taxManagement/urls.py
from django.urls import path

from taxManagement import views

app_name = 'taxManagement'
urlpatterns = [
    path('upload/', views.upload_excel_sheet, name='upload-tax'),
    path('list/uploaded-invoices', views.get_all_invoice_headers , name='get-all-invoice-headers'),
    path('connect/get-data', views.import_data_from_db , name='connect-oracle'),

    # path('invoice-headers/' , views.get_all_invoice_headers , name='get-all-invoice-headers')
    path('list/eta-invoice/', views.list_eta_invoice, name='list-eta-invoice'),
    path('submit-invoice/<slug:invoice_id>', views.submit_invoice , name='submit-invoice'),
    path('document-detail/<slug:internal_id>/', views.get_decument_detail_after_submit , name='dec-detail'),
    path('upload-excel-sheet/' , views.upload_excel_sheet, name='upload-excel-sheet'),
    path('resubmit-invoice/<slug:invoice_id>', views.resubmit, name='resubmit-invoice'),
    path('view-invoice/<slug:invoice_id>' , views.view_invoice , name = 'view-invoice'),
    path('create-invoice-header' , views.create_new_invoice_header , name='create-invoice-header'),
    path('create-invoice-line/<int:invoice_id>' , views.create_new_invoice_line , name='create-invoice-line'),
    path('refresh-submission-status/<slug:submission_id>' , views.refresh_submission_status , name='refresh-submission-status'),

    path('tax/change-invoice-status/<int:invoice_id>/<slug:status>', views.update_invoice_status, name="update-invoice-status"),

    path('export/invoice-template', views.export_empty_invoice_temp, name="export_excel_template"),

    path('ajax/load-addresses/', views.load_receiver_addresses, name='ajax_load_addresses'),

    path('cancel-invoice/<slug:doc_uuid>/', views.cancel_document_form, name="cancel_doc_form"),

    path('list/print-invoice/', views.list_print_invoice, name='list_print_invoice'),
    path('print-invoice/<slug:doc_uuid>', views.print_invoice, name='print_invoice'),
    path('ajax/load-subtasks/', views.load_subtasks, name='ajax_load_subtasks'),

]

boxMate/taxManagement/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum
from django.db.models.signals import pre_save
from django.dispatch import receiver
from issuer.models import Issuer, Receiver, Address, IssuerActivityCode
from codes.models import ActivityType, UnitType
from codes.models import TaxSubtypes, TaxTypes
from datetime import datetime
from django.conf import settings
from currencies.models import Currency


# Create your models here.


class MainTable(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    # Core
    document_type = models.CharField(max_length=20, blank=True, null=True)
    document_type_version = models.CharField(max_length=20, blank=True, null=True)
    date_time_issued = models.DateTimeField(blank=True, null=True)
    taxpayer_activity_code = models.CharField(max_length=20, blank=True, null=True)
    internal_id = models.CharField(max_length=20, blank=True, null=True)
    purchase_order_reference = models.CharField(max_length=55, blank=True, null=True)
    purchase_order_description = models.CharField(max_length=55, blank=True, null=True)
    sales_order_reference = models.CharField(max_length=20, blank=True, null=True)
    sales_order_description = models.CharField(max_length=20, blank=True, null=True)
    proforma_invoice_number = models.CharField(max_length=50, blank=True, null=True)
    total_sales_amount = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    total_discount_amount = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    net_amount = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    total_amount = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    total_items_discount_amount = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    extra_discount_amount = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)

    # Issuer
    issuer_type = models.CharField(max_length=55, blank=True, null=True)
    issuer_registration_num = models.CharField(max_length=20, blank=True, null=True)
    issuer_name = models.CharField(max_length=55, blank=True, null=True)
    issuer_building_num = models.CharField(max_length=55, blank=True, null=True)
    issuer_room = models.CharField(max_length=20, blank=True, null=True)
    issuer_floor = models.CharField(max_length=29, blank=True, null=True)
    issuer_street = models.CharField(max_length=55, blank=True, null=True)
    issuer_land_mark = models.CharField(max_length=55, blank=True, null=True)
    issuer_additional_information = models.CharField(max_length=55, blank=True, null=True)
    issuer_governate = models.CharField(max_length=55, blank=True, null=True)
    issuer_region_city = models.CharField(max_length=55, blank=True, null=True)
    issuer_postal_code = models.CharField(max_length=20, blank=True, null=True)
    issuer_country = models.CharField(max_length=20, blank=True, null=True)
    issuer_branch_id = models.CharField(max_length=20, blank=True, null=True)

    # Receiver
    receiver_type = models.CharField(max_length=55, blank=True, null=True)
    receiver_registration_num = models.CharField(max_length=20, blank=True, null=True)
    receiver_name = models.CharField(max_length=55, blank=True, null=True)
    receiver_building_num = models.CharField(max_length=55, blank=True, null=True)
    receiver_room = models.CharField(max_length=20, blank=True, null=True)
    receiver_floor = models.CharField(max_length=5, blank=True, null=True)
    receiver_street = models.CharField(max_length=55, blank=True, null=True)
    receiver_land_mark = models.CharField(max_length=55, blank=True, null=True)
    receiver_additional_information = models.CharField(max_length=55, blank=True, null=True)
    receiver_governate = models.CharField(max_length=55, blank=True, null=True)
    receiver_region_city = models.CharField(max_length=55, blank=True, null=True)
    receiver_postal_code = models.CharField(max_length=20, blank=True, null=True)
    receiver_country = models.CharField(max_length=20, blank=True, null=True)

    # Payment
    bank_name = models.CharField(max_length=20, blank=True, null=True)
    bank_address = models.CharField(max_length=20, blank=True, null=True)
    bank_account_no = models.CharField(max_length=55, blank=True, null=True)
    bank_account_iban = models.CharField(max_length=55, blank=True, null=True)
    swift_code = models.CharField(max_length=20, blank=True, null=True)
    payment_terms = models.CharField(max_length=20, blank=True, null=True)

    # Delivery
    approach = models.CharField(max_length=20, blank=True, null=True)
    packaging = models.CharField(max_length=20, blank=True, null=True)
    date_validity = models.DateTimeField(blank=True, null=True)
    export_port = models.CharField(max_length=55, blank=True, null=True)
    country_of_origin = models.CharField(max_length=55, blank=True, null=True)
    gross_weight = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    net_weight = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    delivery_terms = models.CharField(max_length=55, blank=True, null=True)

    # Tax Total
    taxt_type = models.CharField(max_length=55, blank=True, null=True)
    tax_amount = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)

    # Signature
    signature_type = models.CharField(max_length=55, blank=True, null=True)
    signature_value = models.CharField(max_length=200, blank=True, null=True)

    # Invoice Line
    description = models.CharField(max_length=55, blank=True, null=True)
    item_type = models.CharField(max_length=20, blank=True, null=True)
    item_code = models.CharField(max_length=55, blank=True, null=True)
    unit_type = models.CharField(max_length=20, blank=True, null=True)
    quantity = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    sales_total = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    internal_code = models.CharField(max_length=20, blank=True, null=True)
    items_discount = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    net_total = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    total_taxable_fees = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    value_difference = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    total = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    # Value
    currency_sold = models.CharField(max_length=20, blank=True, null=True)
    amount_sold = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    amount_egp = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    currency_exchange_rate = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    # Discount
    discount_rate = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    discount_amount = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    # Taxable Item
    taxt_item_type = models.CharField(max_length=55, blank=True, null=True)
    tax_item_amount = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    tax_item_subtype = models.CharField(max_length=55, blank=True, null=True)
    tax_item_rate = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)


class InvoiceHeader(models.Model):
    issuer = models.ForeignKey(Issuer, on_delete=models.CASCADE, null=True, blank=True)
    issuer_address = models.ForeignKey(Address, on_delete=models.CASCADE, null=True, blank=True,
                                       related_name="issuer_address")
    receiver = models.ForeignKey(Receiver, on_delete=models.CASCADE, related_name="receiver_val")
    receiver_address = models.ForeignKey(Address, on_delete=models.CASCADE, null=True, blank=True,
                                         related_name="receiver_address")
    document_type = models.CharField(max_length=2,
                                     choices=[('I', 'Invoice'),('C','Credit Memo'),('D','Debit Memo')], default='I')
    document_type_version = models.CharField(max_length=8,
                                             choices=[('1.0', '1.0'), ('0.9', '0.9')], default='1.0')

    date_time_issued = models.DateTimeField(default=datetime.now())
    taxpayer_activity_code = models.ForeignKey(IssuerActivityCode, on_delete=models.CASCADE)
    internal_id = models.CharField(max_length=50)
    purchase_order_reference = models.CharField(max_length=50, null=True, blank=True)
    purchase_order_description = models.CharField(max_length=100, null=True, blank=True)
    sales_order_reference = models.CharField(max_length=50, null=True, blank=True)
    sales_order_description = models.CharField(max_length=100, null=True, blank=True)
    proforma_invoice_number = models.CharField(max_length=50, null=True, blank=True)
    total_sales_amount = models.DecimalField(decimal_places=5, max_digits=20, null=True, blank=True, default=0.0)
    total_discount_amount = models.DecimalField(decimal_places=5, max_digits=20, null=True, blank=True, default=0.0)
    net_amount = models.DecimalField(decimal_places=5, max_digits=20, null=True, blank=True, default=0.0)
    extra_discount_amount = models.DecimalField(decimal_places=5, max_digits=20, null=True, blank=True, default=0.0)
    total_items_discount_amount = models.DecimalField(decimal_places=5, max_digits=20, null=True, blank=True,
                                                      default=0.0)
    total_amount = models.DecimalField(decimal_places=5, max_digits=20, null=True, blank=True, default=0.0)

boxMate/taxManagement/api/views.py
import json

import requests
from django.shortcuts import render
from requests.auth import HTTPBasicAuth
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from taxManagement.resources import MainTableResource
from tablib import Dataset
from django.conf import settings
from taxManagement.tmp_storage import TempFolderStorage
from django.db.models import Count
from taxManagement.models import MainTable, InvoiceHeader, InvoiceLine, TaxTypes, TaxLine, Signature , Submission
from issuer.models import Issuer, Receiver
from codes.models import ActivityType, TaxSubtypes, TaxTypes
from rest_framework.decorators import api_view
from issuer.models import *
from codes.models import *
from pprint import pprint
from decimal import Decimal
from .serializers import InvoiceHeaderSerializer , SubmissionSerializer


@api_view(['POST', ])
def upload_excel_sheet(request):
    main_table_resource = MainTableResource()
    import_file = request.FILES['import_file']
    dataset = Dataset()
    # # unhash the following line in case of csv file
    # # imported_data = dataset.load(import_file.read().decode(), format='csv')
    imported_data = dataset.load(import_file.read(), format='xlsx')  # this line in case of excel file
    #
    result = main_table_resource.import_data(imported_data, dry_run=False)  # Test the data import
    tmp_storage = write_to_tmp_storage(import_file)
    if not result.has_errors() and not result.has_validation_errors():
        tmp_storage = TMP_STORAGE_CLASS(name=tmp_storage.name)
        data = tmp_storage.read('rb')
        # Uncomment the following line in case of 'csv' file
        # data = force_str(data, "utf-8")
        dataset = Dataset()
        # Enter format = 'csv' for csv file
        imported_data = dataset.load(data, format='xlsx')

        result = main_table_resource.import_data(imported_data,
                                                 dry_run=False,
                                                 raise_errors=True,
                                                 file_name=tmp_storage.name, )
        tmp_storage.remove()

    else:
        print(result.base_errors)
        data = {"success": False, "error": {"code": 400, "message": "Invalid Excel sheet"}}
        return Response(data, status=status.HTTP_400_BAD_REQUEST)
    data = {"success": True}
    return Response(data, status=status.HTTP_200_OK)



@api_view(['GET',])
def get_all_invoice_headers(request):
    invoice_headers = InvoiceHeader.objects.all()
    # headers = []
    # for invoice_header in invoice_headers:
    #     header = get_invoice_header(invoice_header.internal_id)
    #     headers.append(header)
    if request.method == 'GET':
        serializer =  InvoiceHeaderSerializer(invoice_headers , many=True)
        return Response(serializer.data , status=status.HTTP_200_OK)



@api_view(['GET', ])
def submission_list(request):
    submissions = Submission.objects.all()
    if request.method == 'GET':
        submissions_serializer = SubmissionSerializer(submissions, many=True)
        return Response(submissions_serializer.data)

boxMate/taxManagement/templates/cancel_document_form.html
{% extends 'main.html'%}
{% load static %}
{% load l10n %}
{% load i18n %}

{% block body %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            {% trans 'Cancellation Form' %}
        </h1>

    </section>
    <!-- Main content -->
    <section class="content">
        {% include 'messages.html' %}
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">{% trans 'Cancel Invoice Form' %}</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <!--                            form-->
                        <form method="POST" id="doc_cancel_form" action="{% url 'taxManagement:cancel_doc_form' doc_uuid=uuid %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="cancel_reason">Cancellation Reason</label>
                                <input class="form-control" name="cancel_reason" id="cancel_reason" placeholder="Example: wrong taxpayer information">
                            </div>
                            <button type="submit" class="btn btn-primary mb-2">Cancel Form</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock body %}

boxMate/taxManagement/templates/receiver-addresses-dropdown.html
<option value="">---------</option>
{% for address in addresses %}
<option value="{{ address.pk }}">{{ address.branch_id }}</option>
{% endfor %}

boxMate/taxManagement/templates/subtask_dropdown_list_options.html
<option value="">---------</option>
{% for subtask in subtasks %}
<option value="{{ subtask.pk }}">{{ subtask.code }}</option>
{% endfor %}

boxMate/taxManagement/templates/upload-invoice.html
{% extends 'main.html'%}
{% load static %}
{% load l10n %}
{% load i18n %}

{% block body %}
<div class="content-wrapper">
   <!-- Content Header (Page header) -->
   <section class="content-header">

      <h1>
         {% trans "Upload Invoice" %}
         <!-- <small>Optional description</small> -->
      </h1>

   </section>
   <!-- Main content -->
   <section class="content">
      {% include 'messages.html' %}

      <div class="row">
         <div class="col-xs-12">
            <div class="box">
               <div class="box-header">
                  <h3 class="box-title"></h3>
               </div>
               <!-- /.box-header -->
               <div class="box-body">
                  <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                     <div class="row">
                        <div class="col-sm-6">
                           <div class="dataTables_length" id="example1_length">
                              <label>
                                 Show
                                 <select name="example1_length" aria-controls="example1" class="form-control input-sm">
                                    <option value="10">10</option>
                                    <option value="25">25</option>
                                    <option value="50">50</option>
                                    <option value="100">100</option>
                                 </select>
                                 entries
                              </label>
                           </div>
                        </div>
                        <div class="col-sm-6">
                           <div id="example1_filter" class="dataTables_filter">
                              <div class="margin pull-right">
                                 <div class="btn-group">
                                    <!-- Button trigger modal -->
                                    <a href="{% url 'taxManagement:create-invoice-header' %}" class="btn btn-success"
                                       style="margin-right: 2px;">
                                       {% trans "Create New Invoice" %}
                                    </a>
                                    <button type="button" class="btn btn-success" data-toggle="modal"
                                       data-target="#exampleModal" style="margin-right: 2px;">
                                       {% trans "Upload Excel" %}
                                    </button>
                                    <a href="{% url 'taxManagement:export_excel_template' %}" class="btn btn-warning">
                                       {% trans 'Export Excel Template' %}
                                    </a>
                                    <!-- <a href="{% url 'taxManagement:connect-oracle' %}">
                                      <button type="button" class="btn btn-success">Import data from OracleDB</button>
                                      </a> -->
                                 </div>

                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="row">
                        <div class="col-sm-12">
                           <table id="example1" class="table table-bordered table-striped dataTable" role="grid"
                              aria-describedby="example1_info">
                              <thead>
                                 <tr role="row">
                                    <th class="col-1">{% trans 'Internal ID' %}</th>
                                    <th class="col-1">{% trans 'Purchase Order Reference' %}</th>
                                    <th>{% trans 'Sales Order Reference' %}</th>
                                    <th>{% trans 'Total Discount Amount' %}</th>
                                    <th>{% trans 'Total Sales Amount' %}</th>
                                    <th>{% trans 'Net Amount' %}</th>
                                    <th>{% trans 'Total Amount' %}</th>
                                    <th style="width: 40px; important!">{% trans 'Submission ID' %}</th>
                                    <th>{% trans 'Submit' %}</th>
                                    <th>{% trans 'Status' %}</th>
                                    <th>View</th>
                                 </tr>
                              </thead>
                              <tbody>
                                 {% for header in invoice_headers %}
                                 <tr>
                                    <td>{{ header.internal_id }}</td>
                                    <td>{{ header.purchase_order_reference }}</td>
                                    <td>{{ header.sales_order_reference }}</td>
                                    <td>{{ header.total_discount_amount }}</td>
                                    <td>{{ header.total_sales_amount }}</td>
                                    <td>{{ header.net_amount }}</td>
                                    <td>{{ header.total_amount }}</td>
                                    {% if header.submissions %}
                                    <td>{{header.submissions.subm_id}}</td>
                                    {% if header.submissions.subm_id %}
                                    <td><span class="label label-success">Submitted</span></td>
                                    {% else %}
                                    <td><span class="label label-danger">Not Submitted</span></td>
                                    {% endif %}

                                    {% else %}
                                    <td></td>
                                    {% if header.invoice_status == 'verified' %}
                                    <td>
                                       <div class="btn-group">
                                         <a href="{% url 'taxManagement:submit-invoice' invoice_id=header.id %}">
                                           <button class="btn btn-primary btn-sm dropdown-toggle">Submit</button>
                                         </a>
                                       </div>
                                    </td>
                                    {% else %}
                                    <td></td>
                                    {% endif %}
                                    <!--  end if invoice status    -->
                                    {% endif %}
                                    {% if header.invoice_status == 'verified' %}
                                       <td><span class="label label-success">{% trans 'Verified' %}</span></td>
                                    {% elif header.invoice_status == 'cancel' %}
                                       <td><span class="label label-danger">{% trans 'Cancelled' %}</span></td>
                                    {% else %}
                                      <td><span class="label label-info">{% trans 'Draft' %}</span></td>
                                    {% endif %}
                                    <td>
                                       <a href="{% url 'taxManagement:view-invoice' invoice_id=header.id %}">
                                          <span class="glyphicon glyphicon-pencil"></span>
                                    </td>
                                    </a>
                                 </tr>
                                 {% endfor %}
                              </tbody>

                           </table>
                        </div>
                     </div>
                     <div class="row">
                        <div class="col-sm-5">
                           <div class="dataTables_info" id="example1_info" role="status" aria-live="polite">Showing 1 to
                              10 of 57 entries</div>
                        </div>
                        <div class="col-sm-7">
                           <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                              <ul class="pagination">
                                 <li class="paginate_button previous disabled" id="example1_previous"><a href="#"
                                       aria-controls="example1" data-dt-idx="0" tabindex="0">Previous</a></li>
                                 <li class="paginate_button active"><a href="#" aria-controls="example1" data-dt-idx="1"
                                       tabindex="0">1</a></li>
                                 <li class="paginate_button "><a href="#" aria-controls="example1" data-dt-idx="2"
                                       tabindex="0">2</a></li>
                                 <li class="paginate_button "><a href="#" aria-controls="example1" data-dt-idx="3"
                                       tabindex="0">3</a></li>
                                 <li class="paginate_button "><a href="#" aria-controls="example1" data-dt-idx="4"
                                       tabindex="0">4</a></li>
                                 <li class="paginate_button "><a href="#" aria-controls="example1" data-dt-idx="5"
                                       tabindex="0">5</a></li>
                                 <li class="paginate_button "><a href="#" aria-controls="example1" data-dt-idx="6"
                                       tabindex="0">6</a></li>
                                 <li class="paginate_button next" id="example1_next"><a href="#"
                                       aria-controls="example1" data-dt-idx="7" tabindex="0">Next</a></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <!-- /.box-body -->
            </div>
            <!-- /.box -->
         </div>
         <!-- /.col -->
      </div>
      <!-- /.row -->
   </section>
</div>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
   aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <form method="POST" action="{% url 'taxManagement:upload-excel-sheet' %}" id="form1"
            enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal-body">
               <input type="file" name="import_file">
            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
               <button type="submit" class="btn btn-secondary" data-dismiss="modal"
                  onclick="document.getElementById('form1').submit();">Submit</button>

            </div>
         </form>
      </div>
   </div>
</div>
{% endblock body %}